# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-04 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/producto/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='rutas',
            field=models.CharField(blank=True, choices=[('MTO', 'Obtener Bajo Pedido (MTO)')], default='MTO', max_length=255, null=True),
        ),
    ]
