# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-06 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0002_auto_20200604_1724'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='almacen',
            options={'verbose_name': 'Almacen', 'verbose_name_plural': 'Almacenes'},
        ),
        migrations.AlterModelOptions(
            name='categoria_producto',
            options={'verbose_name': 'Categoria de Producto', 'verbose_name_plural': 'Categorias de Productos'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='secuencia_referencia',
            options={'verbose_name': 'Secuencia de Referencia', 'verbose_name_plural': 'Secuencias de Referencia'},
        ),
        migrations.AlterModelOptions(
            name='tipo_operacion',
            options={'verbose_name': 'Tipo de Operacion', 'verbose_name_plural': 'Tipos de Operaciones'},
        ),
        migrations.AlterModelOptions(
            name='ubicaciones',
            options={'verbose_name': 'Ubicacion', 'verbose_name_plural': 'Ubicaciones'},
        ),
        migrations.AlterField(
            model_name='categoria_producto',
            name='logistica',
            field=models.CharField(blank=True, choices=[('FIFO', 'First In First Out (FIFO)'), ('LIFO', 'Last In First Out (LIFO)')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='rutas',
            field=models.BooleanField(choices=[('MTO', 'Obtener Bajo Pedido (MTO)')], default=False, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tipo_operacion',
            name='tipo_de_operacion_choice',
            field=models.CharField(blank=True, choices=[('En', 'Envio'), ('Re', 'Recibo'), ('Ti', 'Transferencia Interna')], max_length=255, null=True),
        ),
    ]
