# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-06 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0005_auto_20200606_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opciones_rutas',
            name='mto_obtener_bajo_pedido',
        ),
        migrations.AddField(
            model_name='opciones_rutas',
            name='nombre',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
