# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-08 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Contacto', '0004_compania_nota_interna'),
        ('Inventario', '0006_auto_20200606_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recepcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_programada', models.DateTimeField(auto_now=True)),
                ('documento_origen', models.CharField(blank=True, max_length=255, null=True)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventario.Producto')),
                ('recibir', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Contacto.Individual')),
                ('tipo_operacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.Tipo_Operacion')),
            ],
        ),
    ]
