# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-23 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0008_auto_20200608_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recepcion',
            name='producto',
        ),
        migrations.AddField(
            model_name='recepcion',
            name='producto',
            field=models.ManyToManyField(blank=True, to='Inventario.Producto'),
        ),
    ]
