# Generated by Django 2.2.16 on 2020-10-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0010_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicaciones',
            name='estrategia_retirada',
            field=models.CharField(blank=True, choices=[('FIFO', 'First In First Out (FIFO)'), ('LIFO', 'Last In First Out (LIFO)')], max_length=255, null=True),
        ),
    ]
