# Generated by Django 2.2.16 on 2020-10-15 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0011_ubicaciones_estrategia_retirada'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepcion',
            name='nota',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Contacto.Individual'),
        ),
    ]
