# Generated by Django 2.2.16 on 2020-10-15 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Contacto', '0006_compania_tipo_contacto_choice'),
        ('Inventario', '0012_auto_20201015_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria_Unidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Categoria de Medida',
                'verbose_name_plural': 'Categorias de Medidas',
            },
        ),
        migrations.AddField(
            model_name='recepcion',
            name='estado',
            field=models.CharField(choices=[('Bor', 'Borrador'), ('Esp', 'En Espera'), ('Rea', 'Realizado')], default='Bor', max_length=255),
        ),
        migrations.AddField(
            model_name='recepcion',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsable_recepcion', to='Contacto.Individual'),
        ),
        migrations.AddField(
            model_name='tipo_operacion',
            name='ubicacion_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ubicacion_destino_ubicaciones', to='Inventario.Ubicaciones'),
        ),
        migrations.AddField(
            model_name='tipo_operacion',
            name='ubicacion_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ubicacion_origen_ubicaciones', to='Inventario.Ubicaciones'),
        ),
        migrations.CreateModel(
            name='Unidades_Medida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad_de_medida', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('1', 'Mas grande que la unidad de medida de referencia'), ('2', 'Unidad de medida de referencia para esta categoria'), ('3', 'Mas pequeña que la unidad de medida de referencia')], default='1', max_length=255)),
                ('ratio', models.FloatField()),
                ('activo', models.BooleanField(default=True)),
                ('precision_redondeo', models.FloatField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.Categoria_Unidades')),
            ],
            options={
                'verbose_name': 'Unidad de Medida',
                'verbose_name_plural': 'Unidades de Medida',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='udm_compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='udm_compra', to='Inventario.Unidades_Medida'),
        ),
        migrations.AddField(
            model_name='producto',
            name='udm_venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='udm_venta', to='Inventario.Unidades_Medida'),
        ),
    ]
