# Generated by Django 2.2.16 on 2020-10-15 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Contacto', '0006_compania_tipo_contacto_choice'),
        ('Inventario', '0013_auto_20201015_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rutas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='almacen',
            name='albaranes_entrada',
            field=models.CharField(choices=[('1', 'Recibir bienes directamente (1 paso)'), ('2', 'Recibir bienes en la ubicación de entrada y luego llevar a existencias (2 pasos)'), ('3', 'Recibir bienes en la ubicación de entrada, transferir a ubicación de control de calidad, y luego llevar a existencias (3 pasos)')], default='1', max_length=255),
        ),
        migrations.AddField(
            model_name='almacen',
            name='comprar_para_resurtir',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='almacen',
            name='envios_salientes',
            field=models.CharField(choices=[('1', 'Entregar bienes directamente (1 paso)'), ('2', 'Enviar bienes a ubicación de salida y entregar (2 pasos)'), ('3', 'Empaquetar, transferir bienes a ubicación de salida, y enviar (3 pasos)')], default='1', max_length=255),
        ),
        migrations.AddField(
            model_name='tipo_operacion',
            name='crear_nuevo_lote_serie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tipo_operacion',
            name='mover_paquetes_completos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tipo_operacion',
            name='utilizar_existentes_lote_seria',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Reglas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('accion', models.CharField(choices=[('1', 'Obtener desde'), ('2', 'Empujar A'), ('3', 'Jalar & Empujar'), ('4', 'Comprar')], default='1', max_length=255)),
                ('movimiento_automatico', models.CharField(choices=[('1', 'Operacion Manual'), ('2', 'Automatico paso no añadido')], default='1', max_length=255)),
                ('metodo_suministro', models.CharField(choices=[('1', 'Obtene del Stock'), ('2', 'Activa otra regla'), ('3', 'Tomar de almacen, si no esta disponible, active otra regla')], default='1', max_length=255)),
                ('plazo_entrega', models.PositiveIntegerField(default=0)),
                ('compania', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Contacto.Compania')),
                ('ruta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventario.Rutas')),
                ('tipo_operacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operacion_regla', to='Inventario.Tipo_Operacion')),
                ('ubicacion_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ubicacion_reglas_destino', to='Inventario.Ubicaciones')),
                ('ubicacion_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ubicacion_reglas_origen', to='Inventario.Ubicaciones')),
            ],
            options={
                'verbose_name': 'Recepcion',
                'verbose_name_plural': 'Recepciones',
            },
        ),
    ]
