# Generated by Django 2.2.16 on 2020-10-15 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Contacto', '0006_compania_tipo_contacto_choice'),
        ('Inventario', '0014_auto_20201015_1517'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reglas',
            options={'verbose_name': 'Regla', 'verbose_name_plural': 'Reglas'},
        ),
        migrations.AlterModelOptions(
            name='rutas',
            options={'verbose_name': 'Ruta', 'verbose_name_plural': 'Rutas'},
        ),
        migrations.AddField(
            model_name='rutas',
            name='almacenes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rutas',
            name='categoria_producto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rutas',
            name='compania',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Contacto.Compania'),
        ),
        migrations.AddField(
            model_name='rutas',
            name='linea_pedido_ventas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rutas',
            name='productos',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rutas',
            name='reglas',
            field=models.ManyToManyField(blank=True, related_name='rutas_reglas', to='Inventario.Reglas'),
        ),
        migrations.AddField(
            model_name='rutas',
            name='ruta',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reglas',
            name='ruta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reglas_rutas', to='Inventario.Rutas'),
        ),
    ]
