# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-08 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compania',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_contacto_choice', models.CharField(choices=[('Ind', 'Individual'), ('Comp', 'Compañia')], default='Ind', max_length=255)),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('rif', models.CharField(blank=True, max_length=30, null=True)),
                ('telefono', models.CharField(blank=True, max_length=8, null=True)),
                ('movil', models.CharField(blank=True, max_length=8, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('pagina', models.URLField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos/contacto/')),
            ],
        ),
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('abreviatura', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('compania_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Contacto.Compania')),
                ('cedula', models.CharField(blank=True, max_length=8, null=True)),
                ('tipo_direccion', models.CharField(blank=True, choices=[('con', 'Contacto'), ('fact', 'Direccion de Factura'), ('ent', 'Direccion de Entrega'), ('otr', 'Otra Direccion'), ('priv', 'Direccion Privada')], max_length=255, null=True)),
                ('puesto_trabajo', models.CharField(blank=True, max_length=30, null=True)),
                ('compania', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relacion_compania', to='Contacto.Compania')),
                ('titulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Contacto.Titulo')),
            ],
            bases=('Contacto.compania',),
        ),
    ]
