# Generated by Django 2.2.16 on 2020-10-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contacto', '0005_compania_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='compania',
            name='tipo_contacto_choice',
            field=models.CharField(choices=[('Ind', 'Individual'), ('Comp', 'Compañia')], default='Ind', max_length=255),
        ),
    ]
